In [1]:
import pandas as pd

In [54]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [55]:
# show columns with number of null records using isnull()
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [57]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

# Drop Null Record

In [58]:
# dropna()
# If we need to change data permanently use inplace = True.
# df.dropna(inplace = True)

In [59]:
'''
axis -> 0 (Row) and 1 (Column)
how -> any / all

dropna(axis=0, how='any', inplace=False) -> default
'''

"\naxis -> 0 (Row) and 1 (Column)\nhow -> any / all\n\ndropna(axis=0, how='any', inplace=False) -> default\n"

In [60]:
# df.dropna(axis=1, how='any', inplace=True)

# Fill Null Data

In [61]:
'''
Mean, Median, Mode, Custom Record
--------------------------------------
Mean and Median -> Numeric Record
Mode -> Categorical
Custom Record for both.
'''

'\nMean, Median, Mode, Custom Record\n--------------------------------------\nMean and Median -> Numeric Record\nMode -> Categorical\nCustom Record for both.\n'

In [62]:
# Commission -> Mean, Median
# ManagerId, DepartmentId -> Mode

In [63]:
sal_mean = df['COMMISSION_PCT'].mean()
sal_mean

np.float64(0.22285714285714284)

In [64]:
# Integer / Float
round_sal_mean = round(sal_mean, 2)
round_sal_mean

np.float64(0.22)

In [65]:
# Format to string
fmt_sal_mean = f'{sal_mean:,.2f}'
fmt_sal_mean

'0.22'

In [41]:
# sal_median = df['COMMISSION_PCT'].median()
# sal_median

In [67]:
# Fillna(inplace = True)
# df['COMMISSION_PCT'].fillna(round_sal_mean, inplace=True)
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(round_sal_mean)

In [68]:
df['COMMISSION_PCT'].unique()

array([0.22, 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])

In [69]:
df['MANAGER_ID'].unique()

array([ nan, 100., 102., 103., 101., 108., 114., 120., 121., 122., 123.,
       124., 145., 146., 147., 148., 149., 201., 205.])

In [70]:
df['DEPARTMENT_ID'].unique()

array([ 90.,  60., 100.,  30.,  50.,  80.,  nan,  10.,  20.,  40.,  70.,
       110.])

In [80]:
man_mode = df['MANAGER_ID'].mode()[0]
man_mode

np.float64(100.0)

In [88]:
dep_mode = df['DEPARTMENT_ID'].mode()[0]
dep_mode

np.float64(50.0)

In [86]:
# df.isnull().sum()

In [83]:
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(man_mode)

In [84]:
df['DEPARTMENT_ID']  = df['DEPARTMENT_ID'].fillna(dep_mode)

In [91]:
fraud = pd.read_csv('Dataset/Fraud Detection Dataset.csv')
fraud.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

fraud.isnull().sum()

In [95]:
fraud['Transaction_Amount'].median()

2524.1000000000004

In [99]:
fraud['Device_Used'].unique()

array(['Tablet', 'Mobile', 'Desktop', 'Unknown Device'], dtype=object)

In [98]:
fraud['Device_Used'] = fraud['Device_Used'].fillna('Unknown Device')

In [101]:
fraud['Location'].unique()

array(['San Francisco', 'New York', nan, 'Chicago', 'Boston', 'Houston',
       'Miami', 'Los Angeles', 'Seattle'], dtype=object)

In [102]:
fraud['Payment_Method'].unique()

array(['Debit Card', 'Credit Card', nan, 'UPI', 'Net Banking',
       'Invalid Method'], dtype=object)

In [103]:
fraud['Time_of_Transaction'].unique()

array([16., 13., nan, 15., 19.,  2.,  3., 20.,  0., 12., 21., 14.,  7.,
        4., 17., 10.,  5.,  8., 11., 18.,  1., 22.,  9.,  6., 23.])

In [ ]:
# hr dataset refresh

In [26]:
df = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

# Remove unwanted data from dataset

In [27]:
# use replace() function for removing unwanted data and replacing it from some valid text or spaces.

In [28]:
# regex -> (,./!@#$%^&*()_+-=)
# string.replace(find, replace_value, regex=False)

In [29]:
df['Employee_Name'] = df['Employee_Name'].str.replace(',', ' ', regex=False)

# Remove unwanted space (white-spaces)

In [30]:
# Categorical Records
df['Position'].unique()

array(['Production Technician I', 'Sr. DBA', 'Production Technician II',
       'Software Engineer', 'IT Support', 'Data Analyst',
       'Database Administrator', 'Enterprise Architect', 'Sr. Accountant',
       'Production Manager', 'Accountant I', 'Area Sales Manager',
       'Software Engineering Manager', 'BI Director',
       'Director of Operations', 'Sr. Network Engineer', 'Sales Manager',
       'BI Developer', 'IT Manager - Support', 'Network Engineer',
       'IT Director', 'Director of Sales', 'Administrative Assistant',
       'President & CEO', 'Senior BI Developer',
       'Shared Services Manager', 'IT Manager - Infra',
       'Principal Data Architect', 'Data Architect', 'IT Manager - DB',
       'Data Analyst ', 'CIO'], dtype=object)

In [31]:
df['State'].unique()

array(['MA', 'TX', 'CT', 'VA', 'VT', 'AL', 'WA', 'CA', 'OH', 'IN', 'TN',
       'NH', 'RI', 'PA', 'CO', 'NY', 'UT', 'GA', 'FL', 'NC', 'KY', 'ID',
       'NV', 'MT', 'OR', 'ND', 'AZ', 'ME'], dtype=object)

In [36]:
columns = ['Position', 'State', 'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
          'TermReason', 'EmploymentStatus', 'Department', 'RecruitmentSource', 'PerformanceScore']
for col in columns:
    u_col = df[col].unique()
    print(col)
    print('-'*55)
    print(f'{u_col}\n')

Position
-------------------------------------------------------
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'CIO']

State
-------------------------------------------------------
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']

Gender
-------------------------------------------------------
['M' 'F']

MaritalDesc
-------------------------------------------------------
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']

CitizenDesc
-------------------------------------------------------
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']

HispanicLatino
-------------------------------------------------------
['No' 'Yes']

RaceDesc
-------------------------------------------------------
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']

TermReason
-------------------------------------------------------
['N/A-StillEmployed' 'career change' 'hours' 'return to school'
 'Another position' 'unhappy' 'attendance' 'performance'
 'Learned that he is a gangster' 'retiring' 'relocation out of area'
 'more money' 'military' 'no-call, no-show' 'Fatal attraction'
 'maternity leave - did not return' 'medical issues' 'gross misconduct']

EmploymentStatus
-------------------------------------------------------
['Active' 'Voluntarily Terminated' 'Terminated for Cause']

Department
-------------------------------------------------------
['Production' 'IT/IS' 'Software Engineering' 'Admin Offices' 'Sales'
 'Executive Office']

RecruitmentSource
-------------------------------------------------------
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']

PerformanceScore
-------------------------------------------------------
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']

In [33]:
# Strip()
strip_columns = ['Position', 'Gender', 'Department']
for st_col in strip_columns:
    df[st_col] = df[st_col].str.strip()

# Label Encoding

In [34]:
# Hispanic Latino
hl_data = {
    'No': 'No',
    'Yes': 'Yes',
    'no': 'No',
    'yes': 'Yes'
}
df['HispanicLatino'] = df['HispanicLatino'].map(hl_data)

In [35]:
df['HispanicLatino'].unique()

array(['No', 'Yes'], dtype=object)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   582 non-null    int64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(1), int64(17), object(18)
memory usage: 163.8+ KB

In [39]:
# df['ManagerID'] = df['ManagerID'].astype(int)

In [41]:
mgr_mode = df['ManagerID'].mode()[0]

In [42]:
df['ManagerID'] = df['ManagerID'].fillna(mgr_mode)

In [43]:
df['ManagerID'] = df['ManagerID'].astype(int)

In [ ]:
'''
Date
------
Format (parameter)
-----------
'%d.%m.%y' -> default
'%d-%m-%y'
'mixed'

dayfirst = True (default = False)

Changed Format -> 'Y-M-D'
'''

In [51]:
df['DOB'] = pd.to_datetime(df['DOB'], format='mixed')

In [52]:
df['DOB']

0     1983-07-10
1     1975-05-05
2     1988-09-19
3     1988-09-27
4     1989-09-08
         ...
577   1989-09-08
578   1977-05-22
579   1979-05-24
580   1983-02-18
581   1970-02-11
Name: DOB, Length: 582, dtype: datetime64[ns]

In [47]:
hr = pd.read_csv('Dataset/Employees.csv')

In [48]:
hr.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [50]:
hr['HIRE_DATE'] = pd.to_datetime(hr['HIRE_DATE'])

In [ ]:
# Split()
# import re
# re.sub()