In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cleaned_hr_data.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,First_Name,Middle_Name,Last_Name,Hire_Year,Hire_Month,Hire_Day,Hire_Month_Name,Hire_Day_Name,HispanicLatinoID,EmpStatus_ID
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Wilson,K,Adinolfi,2011,7,5,July,Tuesday,0,0
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Karthikeyan,NaN,Ait Sidi,2015,3,30,March,Monday,0,1
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Sarah,NaN,Akinkuolie,2011,7,5,July,Tuesday,0,1
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Trina,NaN,Alagbe,2008,1,7,January,Monday,0,0
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Carol,NaN,Anderson,2011,7,11,July,Monday,0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 46 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
 36  First_Name                  582 non-null    object
 37  Middle_Name                 44 non-null     object
 38  Last_Name                   582 non-null    object
 39  Hire_Year                   582 non-null    int64
 40  Hire_Month                  582 non-null    int64
 41  Hire_Day                    582 non-null    int64
 42  Hire_Month_Name             582 non-null    object
 43  Hire_Day_Name               582 non-null    object
 44  HispanicLatinoID            582 non-null    int64
 45  EmpStatus_ID                582 non-null    int64
dtypes: float64(2), int64(21), object(23)
memory usage: 209.3+ KB

In [4]:
# groupby Function
# Aggregate Function
'''
- If we peform analysis using aggregate function then group by is not necessary.
- If we perform analysis using group by then aggregate function must be used.

Aggregate Functions
----------------------
Mean(), Max(), Min(), Count(), Sum()

KPIs (Key Peformance Indicator)
'''

'\n- If we peform analysis using aggregate function then group by is not necessary.\n- If we perform analysis using group by then aggregate function must be used.\n\nAggregate Functions\n----------------------\nMean(), Max(), Min(), Count(), Sum()\n\nKPIs (Key Peformance Indicator)\n'

In [5]:
# Find total employees by each gender.
gender_count = df.groupby('Gender')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees'}
)
gender_count

  Gender  Total Employees
0      F              354
1      M              228

In [6]:
# Find total salary distributed to employees by each departments. sum()
dep_sal = df.groupby('Department')['Salary'].sum().reset_index()
dep_sal

             Department    Salary
0         Admin Offices    646127
1      Executive Office    250000
2                 IT/IS   8134411
3            Production  26949336
4                 Sales   2140899
5  Software Engineering   4373364

In [7]:
dep_sal = df.groupby('Department')['Salary'].sum()
# stralign -> String Align -> left, right, center
# numalign -> Number Align -> left, right, center

print(dep_sal.to_markdown(stralign='center', numalign='left'))

|      Department      | Salary      |
|:--------------------:|:------------|
|    Admin Offices     | 646127      |
|   Executive Office   | 250000      |
|        IT/IS         | 8.13441e+06 |
|      Production      | 2.69493e+07 |
|        Sales         | 2.1409e+06  |
| Software Engineering | 4.37336e+06 |

In [8]:
# Print report of an analysis where total salary, total employees, average employee satisfaction,
# total absence days of emplyoees by each department.
# agg() -> aggregate function

dep_details = df.groupby('Department').agg(
    Total_Salary = ('Salary', 'sum'),
    Total_Employees = ('EmpID', 'count'),
    Avg_Emp_Satisfaction = ('EmpSatisfaction', 'mean'),
    Total_Absence = ('Absences', 'sum')
).sort_values(ascending=True, by='Total_Salary').reset_index()

dep_details['Total_Salary'] = dep_details['Total_Salary'].map("Rs.{:,.2f}".format)
dep_details['Avg_Emp_Satisfaction'] = dep_details['Avg_Emp_Satisfaction'].map("{:,.2f}".format)

In [9]:
# abs_data = dep_details['Total_Absence'] < 100
# dep_details[abs_data]
dep_details

,Department,Total_Salary,Total_Employees,Avg_Emp_Satisfaction,Total_Absence
0,Executive Office,"Rs.250,000.00",1,3.00,10
1,Admin Offices,"Rs.646,127.00",9,3.56,78
2,Sales,"Rs.2,140,899.00",31,4.03,358
3,Software Engineering,"Rs.4,373,364.00",40,3.30,647
4,IT/IS,"Rs.8,134,411.00",82,3.63,1048
5,Production,"Rs.26,949,336.00",419,4.00,3914

In [10]:
# Find total employees data by each department and its performance score.
dep_perf = df.groupby(['Department', 'PerformanceScore'])['EmpID'].count().reset_index()
dep_perf

              Department   PerformanceScore  EmpID
0          Admin Offices        Fully Meets      9
1       Executive Office        Fully Meets      1
2                  IT/IS            Exceeds      7
3                  IT/IS        Fully Meets     73
4                  IT/IS  Needs Improvement      1
5                  IT/IS                PIP      1
6             Production            Exceeds     86
7             Production        Fully Meets    310
8             Production  Needs Improvement     15
9             Production                PIP      8
10                 Sales            Exceeds      2
11                 Sales        Fully Meets     24
12                 Sales  Needs Improvement      1
13                 Sales                PIP      4
14  Software Engineering            Exceeds      2
15  Software Engineering        Fully Meets     37
16  Software Engineering  Needs Improvement      1

In [11]:
pef_detail = (dep_perf['PerformanceScore'] == 'Fully Meets') | (dep_perf['PerformanceScore'] == 'Exceeds')
dep_perf[pef_detail]

              Department PerformanceScore  EmpID
0          Admin Offices      Fully Meets      9
1       Executive Office      Fully Meets      1
2                  IT/IS          Exceeds      7
3                  IT/IS      Fully Meets     73
6             Production          Exceeds     86
7             Production      Fully Meets    310
10                 Sales          Exceeds      2
11                 Sales      Fully Meets     24
14  Software Engineering          Exceeds      2
15  Software Engineering      Fully Meets     37

In [19]:
df['Hire_Day_Name'].unique()

['Tuesday', 'Monday', 'Thursday', 'Wednesday', 'Sunday', 'Friday', 'Saturday']
Categories (7, object): ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [18]:
weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
# Categorical -> pandas
df['Hire_Day_Name'] = pd.Categorical(df['Hire_Day_Name'], categories=weekdays)

In [23]:
# Find total employees hired in each day.
hire_day = df.groupby('Hire_Day_Name', observed=False)['EmpID'].count().reset_index()
hire_day

  Hire_Day_Name  EmpID
0        Sunday      6
1        Monday    471
2       Tuesday     77
3     Wednesday      9
4      Thursday     10
5        Friday      6
6      Saturday      3

In [26]:
# print(df['Salary'].sum())
# print(df['EmpID'].count())